[versions]
jackson-version = "2.18.3"
jspecify-version = "1.0.0"
junit-version = "5.11.4"
junit-launcher = "1.11.4"


[libraries]
jackson = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson-version" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify-version" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit-version" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit-version" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-launcher" }
